require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_modular_headers!

target 'RnMatrixExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'
  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  target 'RnMatrixExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  post_install do |installer|
#    flipper_post_install(installer)
  end
end

target 'RnMatrixExample-tvOS' do
  # Pods for RnMatrixExample-tvOS

  target 'RnMatrixExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
